# Generated by Django 5.0.6 on 2024-06-20 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('content', models.TextField(blank=True, default='')),
                ('publication_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
